### ISSUE TITLE
PHP和Typescript的extends没有高亮

### ISSUE THREAD

**Issue by tiansin** [yutent/one-plain#3]
![qq20181205-141503](https://user-images.githubusercontent.com/4232281/49493771-4fa91a80-f898-11e8-9284-26175b178b9d.png)
![qq20181205-141521](https://user-images.githubusercontent.com/4232281/49493772-5041b100-f898-11e8-88ee-68099bd8d984.png)

**Comment by tiansin** [comment]
这个是HTML文件中JavaScript
![qq20181205-164242](https://user-images.githubusercontent.com/4232281/49500989-db2ca680-f8ac-11e8-9acd-b09734d8d79c.png)
![qq20181205-164253](https://user-images.githubusercontent.com/4232281/49500990-db2ca680-f8ac-11e8-90ab-31e2c50c93c6.png)

**Comment by yutent** [comment]
已修复, 并精心优化了一波高亮。
在商店搜索新版更新即可。
