### ISSUE TITLE
常量的颜色是否能可以稍微调整一下呢.

### ISSUE THREAD

**Issue by tiansin** [yutent/one-plain#4]
<img width="417" alt="qq20181211-175642 2x" src="https://user-images.githubusercontent.com/4232281/49792812-9dc58e80-fd6e-11e8-82ee-a28baf8f7b73.png">
<img width="331" alt="qq20181211-175704 2x" src="https://user-images.githubusercontent.com/4232281/49792813-9dc58e80-fd6e-11e8-9a07-2e54a10028c7.png">

现在常量的颜色和关键词一样,这样就可能出现这种高亮的情况.

**Comment by tiansin** [comment]
<img width="609" alt="qq20181211-211804 2x" src="https://user-images.githubusercontent.com/4232281/49803273-47fedf80-fd8a-11e8-9b3d-660acab58ff9.png">
更新到最新版本后,对象类型的变量在调用时,颜色都变成了芒果色,感觉非常的刺眼睛,希望能优化下谢谢了.

**Comment by yutent** [comment]
> <img alt="qq20181211-175642 2x" width="417" src="https://user-images.githubusercontent.com/4232281/49792812-9dc58e80-fd6e-11e8-82ee-a28baf8f7b73.png">
> 
> <img alt="qq20181211-175704 2x" width="331" src="https://user-images.githubusercontent.com/4232281/49792813-9dc58e80-fd6e-11e8-9a07-2e54a10028c7.png">
> 
> 现在常量的颜色和关键词一样,这样就可能出现这种高亮的情况.

你这是在乱用`const`啊。

**Comment by tiansin** [comment]
<img width="723" alt="screen shot 2018-12-12 at 10 57 19" src="https://user-images.githubusercontent.com/4232281/49844187-d6ac4480-fdfc-11e8-939b-b9255e3269dd.png">
不是吧?这是vscode自带的代码片断呀.

**Comment by yutent** [comment]
vscode的ts语法和补全提示, 完全就没有规范可言。简直就像 临时工 写出来的。
跟js的补全和提示相比, 规范性差远了。

**Comment by yutent** [comment]
## [1.3.2] 2018-12-12
- 移除ts的异常语法高亮
- 优化常量的高亮


已经发布新版了, 你更新一下 即可
