### ISSUE TITLE
html标签与文案色调区分

### ISSUE THREAD

**Issue by liuzeming1** [yutent/one-plain#7]
html中Tag与文案色调相差无几，能否把两个文本色调调成其他颜色用于区分
<img width="1021" alt="image" src="https://github.com/yutent/one-plain/assets/78456598/b2f295e3-e475-453c-81e4-c89f80838290">

**Comment by yutent** [comment]
你这个是react的jsx文件吧, 不是html文件。 因为我不写react, 之前没注意到这个。你更新到1.6.7就好了。
